project:
  type: website
  render:
    - 404.qmd
    - index.qmd
    - general/*.qmd
    - part-01/*.qmd
    - part-02/*.qmd
    - part-03/*.qmd
    - part-04/*.qmd
    - part-05/*.qmd
    - part-06/*.qmd
website:
  title: "Produktionswirtschaft"
  repo-url: https://github.com/beyondsimulations/Produktionswirtschaft
  site-url: https://beyondsimulations.github.io/Produktionswirtschaft
  bread-crumbs: true
  sidebar:
    style: floating
    #logo: https://images.beyondsimulations.com/logo/midjourney_square_left.png
    collapse-level: 2
    search: true
    contents:
      - text: "Startseite"
        href: index.qmd
      - text: "***"
      - section: "01 Zeitreihen"
        contents:
          - text: "Vorlesung"
            href: part-01/pw2-lecture-01.pdf
          - text: "Tutorium"
            href: part-01/pw2-tutorial-01.qmd
      - section: "02 Holt-Winters"
        contents:
          - text: "Vorlesung"
            href: part-02/pw2-lecture-02.pdf
          - text: "Tutorium"
            href: part-02/pw2-tutorial-02.qmd
      - section: "03 Beschäftigung"
        contents:
          - text: "Vorlesung"
            href: part-03/pw2-lecture-03.pdf
          - text: "Tutorium"
            href: part-03/pw2-tutorial-03.qmd
      - section: "04 Ressourcenplan"
        contents:
          - text: "Vorlesung"
            href: part-04/pw2-lecture-04.pdf
          - text: "Tutorium"
            href: part-04/pw2-tutorial-04.qmd
      - section: "05 Abläufe"
        contents:
          - text: "Vorlesung"
            href: part-05/pw2-lecture-05.pdf
          - text: "Tutorium"
            href: part-05/pw2-tutorial-05.qmd
      - text: "***"
      - text: "FAQs"
        href: general/faqs.qmd
      - text: "Chat"
        href: general/chat.qmd

  page-footer: 
    center: "Produktionswirtschaft, Tobias Vlćek</br>CC BY-NC-SA 4.0" 
    right: 
      - icon: github
        href: https://github.com/beyondsimulations/Produktionswirtschaft
      - icon: linkedin
        href: https://linkedin.com/in/tobiasvlcek
      - icon: envelope
        href: mailto:workshop@beyondsimulations.com
      - icon: lock
        href: general/privacy.qmd

format:
  html:
    theme: [sandstone, styles.scss]
    toc: true
    highlight-style: arrow
    linkcolor: "#a60000"
    code-copy: true
    code-link: true
    toc-location: right
    code-overflow: wrap
    code-block-bg: true
    code-block-border-left: "#AD1F00"
    include-in-header:
      - general/header.html

  pdf:
    documentclass: report
    geometry:
        - margin=1in
    fontfamily: roboto
    fontfamilyoptions: sfdefault
    colorlinks: true
    include-in-header: 
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        
execute:
  freeze: auto


