---
title: "Häufig gestellte Fragen"
subtitle: "Antworten auf gängige Fragen"

html:
    theme: [sandstone, ../styles.scss]
    highlight-style: breezedark
    linkcolor: "#a60000"
    code-copy: true
    code-link: true
    toc: true
---

## Unbeantwortete Fragen

Falls Sie eine Frage haben, die hier nicht beantwortet wird, teilen Sie mir dies bitte mit, indem Sie mir eine E-Mail an [tobias.vlcek@uni-due.de](mailto:tobias.vlcek@uni-due.de?subject=Produktionswirtschaft%3A%20%3CIhr%20Betreff%3E). Sollten Sie einen Fehler im Kursmaterial gefunden haben oder Vorschläge zur Verbesserung des Kurses haben, teilen Sie mir dies bitte ebenfalls sehr gerne mit!

---

## FAQs

---

## Darf ich ein Blatt mit in die Prüfung nehmen?

Ja, Sie dürfen ein DIN A4-Blatt mit Notizen auf beiden Seiten mit in die Prüfung nehmen. Bitte beachten Sie, dass es sich um **ein** Blatt Papier handeln sollte, das handschriftlich beschrieben sein sollte.

## Kann ich die Übungen auch als PDF herunterladen?

Ja, die Übungen können als PDF herunterladen werden. Die Datei finden Sie auf der jeweiligen Seite der Übung, wenn Sie auf "Typst" klicken.

## Woran orientiert sich die Klausur?

Die Klausur orientiert sich primär an den Probeklausuren von Herrn Manitz und wird die Themen der Vorlesung abdecken, die wir gemeinsam behandelt haben. Wenn ihr die von uns behandelten Themen der alten Klausuren rechnen könnt und die Übungen verstanden habt, seid ihr sehr gut vorbereitet.

## Wie lange dauert die Klausur?

Die Klausur dauert 60 Minuten.




