---
title: "Literature and Resources"
subtitle: "Good books and resources to read"

html:
    theme: [default, ../styles.scss]
    code-copy: true
    code-link: true
    toc: true
    toc-location: right
---

This section provides a curated list of books and resources to enhance your understanding of mathematical Modelling, Julia programming and related topics. Each recommendation includes a brief description to help you choose the most suitable resources for you.

# Julia

## Books
- Lauwens, B., & Downey, A. B. (2019). Think Julia: How to think like a computer scientist (First edition). O’Reilly®. [Link to the free book website](https://benlauwens.github.io/ThinkJulia.jl/latest/book.html).
    - This book is great for beginners and covers Julia programming in a comprehensive manner.
- Kwon, C. (2019). Julia programming for operations research (Second edition). Changhyun Kwon. [Link to the free book website](https://www.chkwon.net/julia/).
    - This book is a fantastic ressource for students interested in Julia and Operations Research and covers a variety of topics.

## Resources
- [Julia Documentation](https://docs.julialang.org/)
    - The official Julia documentation is an good starting point to understand the language's features and syntax.
- [JuMP Documentation](https://jump.dev/JuMP.jl/stable/)
    - The official documentation of JuMP is a great resource for understanding optimization modeling in Julia, covering everything from simple linear models to advanced nonlinear and mixed-integer problems.
    